
--| ENTITIES |--

INSERT INTO entities (name, color, initials, description) 
VALUES ('Universidade do Porto', 'rainbow', 'UP', 'A U.Porto tem por missão a criação de conhecimento científico, cultural e artístico, a formação de nível superior fortemente ancorada na investigação, a valorização social e económica do conhecimento e a participação ativa no progresso das comunidades em que se insere.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Arquitetura', '#FFFFFF', 'FAUP', 'Criada em 1976, a partir do legado da Escola de Belas Artes da U.Porto (ESBAP), a FAUP é uma das mais reputadas reputadas escolas de Arquitetura do mundo. Aqui formaram-se e deram aulas nomes importantes da “Escola do Porto” (uma das mais influentes correntes de Arquitetura contemporânea em Portugal), casos de Álvaro Siza Vieira e Eduardo Souto Moura, os dois únicos arquitetos portugueses distinguidos com o Prémio Pritzker, considerado o “Prémio Nobel” da Arquitetura. Localizado no Polo III (Campo Alegre) da U.Porto, o complexo de edifícios que alberga a FAUP, desde 1992, é também uma das criações mais emblemáticas da carreira de Siza Vieira. Um espaço único que pdoe ser conhecido por qualquer pessoa numa das visitas guiadas organizadas regularmente pela faculdade.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Belas Artes', '#666666', 'FBAUP', 'Situada na zona oriental da cidade do Porto, a alguns minutos do centro histórico, a Faculdade de Belas-Artes ocupa um antigo palacete do século XIX em cujos jardins se construíram, nos anos 50, edifícios de interesse arquitectónico, especialmente concebidos para o ensino das disciplinas tradicionais das Belas-Artes. Desde a sua fundação, em 1836, a Academia de Belas Artes manteve uma política de atribuição de bolsas no estrangeiro aos melhores alunos, que tradicionalmente se encaminhavam para Paris e Roma e enviavam regularmente exemplos do seu trabalho conservados, até hoje, na colecção do Museu da FBAUP. Actualmente, o intercâmbio entre instituições de ensino artístico europeias e a Faculdade de Belas Artes é intenso e continua a crescer tanto ao nível da mobilidade de estudantes como do intercâmbio de professores.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Ciências', '#6FA8DC', 'FCUP', 'Criada em 1911, a Faculdade de Ciências é, a par da Faculdade de Medicina, a mais antiga escola da Universidade do Porto e uma das maiores em estudantes e em produtividade científica. A FCUP é responsável pelo ensino das ciências exatas e naturais e das suas aplicações à tecnologia, oferecendo para tal uma oferta diversificada de cursos de licenciatura, de mestrado integrado, de mestrado e de doutoramento. Os docentes da faculdade integram unidades de investigação de reconhecida excelência o que garante um ensino de elevado padrão internacional. Depois de durante praticamente um século, ter tido a sua “casa” no Edifício História da Universidade, a FCUP encontra-se integrada, desde 2007, nas instalações do Pólo III da Universidade (Campo Alegre). A faculdade mantém ainda ligações efectivas e (ou) históricas a um amplo conjunto de equipamentos que integram o edificado da U.Porto, como o Museu de Ciência, o Museu de História Natural e a Biblioteca do Fundo Antigo (instalados no Edifício Histórico da U.Porto), o Instituto Geofísico / Observatório Meteorológico da Serra do Pilar, o Observatório Astronómico do Professor Manuel de Barros, a Estação de Zoologia Marítima Dr. Augusto Nobre e o Jardim Botânico. O ensino promovido pela Faculdade de Ciências na área das ciência agrárias é também assegurado nas instalações do Campus Agrário de Vairão, em Vila do Conde.');

INSERT INTO entities (name, color, color2, initials, description) 
VALUES ('Faculdade de Ciências da Nutrição e da Alimentação', '#FFFF00', '#38761D', 'FCNAUP', 'Constituída em 1996, a partir do antigo Curso de Nutricionismo da U.Porto, a mais recente unidade orgânica da Universidade do Porto é também uma das mais pioneiras. Afinal, a FCNAUP continua a ser, quase vinte anos após a sua criação, a única faculdade pública portuguesa a conferir o grau de licenciado em Ciências da Nutrição. Mas esta não é a única razão que explica o sucesso da escola. Para além do ensino de excelência, assente numa formação de qualidade elevada desde a pré à pós-graduação, a FCNAUP distingue-se pela investigação interdisciplinar que produz e pelo diálogo permanente que mantém com a comunidade, traduzido numa ampla intervenção (através de campanhas de sensibilização, workshops, entre outras ações) ao nível da promoção de hábitos alimentares saudáveis junto da população. A FCNAUP funciona em instalações provisórias no complexo da Faculdade de Engenharia da U.Porto.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Desporto', '#783F04', 'FADEUP', 'Com origens noutras instituições de formação em Educação Física e Desporto existentes na cidade desde 1964, a Faculdade de Desporto da U.Porto é a escolha ideal para quem pretenda obter formação de ponta no campo do desporto…mas não só. Reunindo uma oferta abrangente de cursos de licenciatura, mestrado e doutoramento, o ensino da FADEUP está fortemente interligado com a investigação em temas fundamentais da sociedade atual, como a relação da atividade física com a saúde e a promoção da qualidade de vida da população. Pelos espaços da faculdade passam também, regularmente, alguns dos melhores atletas portugueses (casos de Nélson Évora, campeão olímpico de triplo salto, ou Vanessa Fernandes, vice-campeã olímpica de triatlo) para usufruírem de algumas das mais bem apetrechadas estruturas de investigação portuguesas ao nível do apoio ao desporto de alto rendimento. Pensadas à imagem das melhores escolas de Educação Física e Desporto a nível mundial, as instalações da FADEUP, situadas na Asprela (Polo II da U.Porto), foram inauguradas em 1997. Para além dos espaços típicos de uma faculdade (salas de aula, laboratórios, biblioteca, auditório, cantina, etc.), o complexo dispõe de espaços vocacionados para a formação/prática desportiva ao mais alto nível, como ginásios, uma piscina, um pavilhão, uma sala de squash, um campo de futebol relvado e uma pista de atletismo.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Direito', '#FF0000', 'FDUP', 'Inaugurada em 1995, a FDUP é uma das mais inovadoras escolas de Direito portuguesas. Afinal, só aqui é possível adquirir formação pré e pós-graduada em Criminologia, área que, a par do Direito, define a oferta formativa da faculdade. Em paralelo, a FDUP destaca-se ainda na criação de conhecimento nos domínios das ciências jurídicas e da ciência do crime. Frequentada atualmente por mais de 1300 estudantes, a faculdade presta também serviços à comunidade no âmbito de protocolos de colaboração celebrados com entidades públicas e privadas em áreas como a com a mediação penal. Depois de ter passado por várias instalações provisórias, a Faculdade de Direito encontra-se sediada, desde 2004, no renovado edifício da Rua dos Bragas, antiga “casa” da Faculdade de Engenharia. No complexo de edifícios vizinhos da FDUP funcionam outras estruturas da U.Porto, como o Polo de Ciências da Comunicação e o Polo de Indústrias Criativas do UPTEC (UPTEC - PINC).');

INSERT INTO entities (name, color, color2, initials, description) 
VALUES ('Faculdade de Economia', '#FF0000', '#FFFFFF', 'FEP', 'Desejo da Universidade desde a sua fundação, foi preciso esperar até 1953 para assistir à criação da Faculdade de Economia. A espera, contudo, valeu a pena…Frequentada por cerca de 3000 estudantes, que ali usufruem de uma ampla oferta formativa nas áreas da Economia e Gestão, a FEP é uma referência nacional e internacional no campo das ciências económicas e empresariais, quer ao nível da educação quer ao nível da investigação científica. A comunidade FEP contempla ainda quase 40 gerações de diplomados e mais de 5000 antigos estudantes a desempenhar funções nos mais diversos setores de actividade. Não é por acaso que a FEP surge frequentemente entre as melhores faculdades de economia do mundo de acordo com alguns dos mais prestigiados rankings do setor. Inaugurado em 1974, o edifício da Faculdade de Economia foi um dos primeiros a ser construídos no Polo II (Asprela) da Universidade do Porto.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Engenharia', '#8C2D19', 'FEUP', 'O ensino das engenharias na Universidade do Porto nasce com a própria universidade, em 1911, a partir da integração dos antigos cursos da Academia Politécnica, culminada, anos mais tarde, com a criação da Faculdade de Engenharia. Atualmente, a FEUP é uma das mais antigas e prestigiadas unidades de ensino e investigação portuguesas no ramo das engenharias e outras áreas contíguas. Um título que se justifica pelo leque variado de formações de elevada qualidade que oferece nos mais variados graus de ensino. Paralelamente, o moderno complexo da faculdade – inaugurado no ano 2000, no Polo 2 (Asprela) – constitui um importante “viveiro” de inovação e conhecimento, alimentado pelo trabalho desenvolvido pelos centros de investigação ali sedeados, em grande proximidade com o tecido empresarial e social.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Farmácia', '#800080', 'FFUP', 'Com origens na escola homónima (anexada à Escola Médico-Cirúrgica) que funcionou até à criação da Universidade do Porto, a FFUP é a mais antiga escola de Farmácia portuguesa. Pioneira no ensino das Ciências Farmacêuticas em Portugal, a FFUP tem a seu cargo um Mestrado Integrado em Ciências Farmacêuticas, a que junta vários segundos ciclos, programas de Doutoramento e um curso de Pós-Graduação de Especialização em Cuidados Farmacêuticos. A aposta na investigação e a colaboração assídua com diversas entidades nacionais e internacionais são outros dos vetores fundamentais da faculdade, fortalecidos em 2012, com a mudança para as instalações do novo complexo ligado às Ciências da Vida e da Saúde (junto ao Palácio de Cristal), que partilha com o ICBAS.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Letras', '#000096', 'FLUP', 'Depois de uma primeira (e curta) existência no início do século XX, a atual Faculdade de Letras da U.Porto foi inaugurada em 1960, com o objetivo de garantir o ensino humanístico na cidade. De então para cá, essa missão tem-se traduzido na prática de uma formação de qualidade em campos tão diversos como a História, a Arqueologia, a Literatura, as Línguas Clássicas, a Filosofia ou, mais recentemente, as Relações Internacionais, as Ciências da Comunicação e o Turismo. Nas últimas décadas, a FLUP vem também reforçando a aposta na produção científica e na prestação de serviços à comunidade, apoiada num corpo docente altamente qualificado, constituído quase exclusivamente por professores doutorados. Ao longo da sua existência, a FLUP funcionou em vários edifícios históricos da U.Porto. Em 1995, foi inaugurado o atual edifício da escola no Campo Alegre (Polo III), “casa” dos mais de 3 mil estudantes que frequentam os cursos de licenciatura, mestrado e doutoramento da faculdade, a que se junta uma variada gama de cursos de formação contínua e de cursos livres (de onde se salientam os cursos de línguas). A FLUP é também a sede do curso de Ciências de Comunicação da U.Porto, a funcionar, desde 2000, no moderno Polo de Ciências da Comunicação, a par de estruturas como o inovador Polo de Indústrias Criativas do UPTEC (UPTEC PINC).');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Medicina', '#FFFF00', 'FMUP', 'Criada em 1911 sob os alicerces da antiga Escola Médico-Cirúrgica, a Faculdade de Medicina é, juntamente com a Faculdade de Ciências, uma das escolas “fundadoras” da Universidade do Porto. Frequentada atualmente por mais de mil estudantes dos vários ciclos de estudo, a FMUP é, a par do ICBAS, uma instituição referência para os estudantes portugueses que pretendem seguir Medicina. Do “cartão de visita” da faculdade destacam-se uma formação de qualidade e com um forte teor prático, a intensa atividade científica e a prestação de serviços à comunidade nas mais diversas áreas da ciência e da prática médicas. Após a sua fundação, a Faculdade de Medicina ocupou o edifício da antiga da Escola Médico-Cirúrgica. Quase meio século depois, a escola mudou-se para as instalações do Hospital de São João, na Asprela (Polo II), dando início a uma colaboração intensa, quer ao nível do ensino e investigação em medicina, como da assistência hospitalar à população. Em 2012, o complexo da FMUP foi enriquecido com um moderno edifício especialmente vocacionado para as atividades de investigação da faculdade.');

INSERT INTO entities (name, color, color2, initials, description) 
VALUES ('Faculdade de Medicina Dentária', '#FFFF00', '#F1C232', 'FMDUP', 'Inaugurada em 1989, a partir da integração na U.Porto da Escola Superior de Medicina Dentária, a Faculdade de Medicina Dentária é uma instituição de prestígio a nível nacional e internacional nos domínios da ensino e da investigação em saúde oral. Para isso contribui a qualidade da formação em medicina Dentária, estimulada por uma forte aposta na produção científica no campo das Ciências Forenses. A estes vetores junta-se uma forte componente ligada aos serviços à comunidade, traduzida, por exemplo, na disponibilização de um amplo espaço/clínica vocacionado para o ensino, mas também para a prestação de cuidados dentários à população, a cargo dos estudantes e docentes da instituição. O atual edifício da FMDUP foi inaugurado em outubro de 1997 e situa-se no Pólo II da Universidade, junto à Estação do Metro de Paranhos. Entre os edifícios “vizinhos” estão o da Faculdade de Psicologia e Ciências da Educação e o do e-Learning Café (Asprela) da U.Porto.');

INSERT INTO entities (name, color, initials, description) 
VALUES ('Faculdade de Psicologia e Ciências da Educação', '#FFA500', 'FPCEUP', 'Inicialmente integrada na Faculdade de Letras, a formação em Psicologia ministrada pela U.Porto ganhou autonomia em 1980, dando origem à atual FPCEUP. Hoje em dia, cerca de 2000 estudantes frequentam a faculdade, distribuídos por um curso de 1º ciclo de estudos conducente à Licenciatura em Ciências da Educação, um de Mestrado Integrado em Psicologia e cursos de pós-graduação, 2º e 3º ciclo conducentes ao Mestrado e ao Doutoramento. Para além do ensino (alimentado ainda por uma oferta alargada de programas de educação contínua), a FPCEUP desenvolve também atividades de I&D e prestação de serviços à comunidade através dos seus institutos e centros de investigação. Depois de quase três décadas a funcionar em instalações provisórias, a FPCEUP encontra-se instalada desde 2005 no edifício projetado pelo famoso arquiteto Fernando Távora (antigo professor da Faculdade de Arquitetura e um dos mentores da “Escola do Porto”) no Pólo II (Asprela).');

INSERT INTO entities (name, color, color2, initials, description) 
VALUES ('Instituto de Ciências Biomédicas Abel Salazar', '#FFFF00', '#6FA8DC', 'ICBAS', 'Criado em 1976, por iniciativa de um grupo de personalidades da U.Porto, entre os quais se destacavam Corino de Andrade, Nuno Grande e Ruy Luís Gomes, e inspirado no pensamento de Abel Salazar, seu patrono, o ICBAS assumiu-se, desde as origens, como uma escola multidisciplinar e multiprofissional na área das Ciências da Vida. Ao apostar numa formação abrangente em áreas como a Medicina, a Veterinária, a Agronomia ou as Ciências do Meio Aquático, mas também na cooperação com diferentes instituições da cidade – designadamente o Hospital Geral de Santo António – e na promoção de serviços especializados à comunidade, o instituto introduziu uma série de princípios inovadores que acompanham a vida da instituição até hoje, fazendo jus ao lema da escola: “um médico que só sabe Medicina nem Medicina sabe”. Depois de mais de 30 anos a funcionar no edifício histórico da Escola Médica, o instituto mudou-se em 2011 para o novo complexo ligado às Ciências da Vida e da Saúde (junto ao Palácio de Cristal, Polo I da U.Porto), o qual partilha com a Faculdade de Farmácia.O ICBAS possui ainda instalações no Campus Agrário de Vairão - em Vila do Conde, paocl de atividades de ensino e investigação científica no campo das ciências veterinárias.');

INSERT INTO entities (name, color, color2, initials, description) 
VALUES ('Porto Business School', '#192AEA', '#FFFFFF', 'PBS', 'Com origens em 1988, a escola de negócios da Universidade do Porto é uma business school em plena afirmação a nível internacional. Beneficiando de uma relação muito próxima com o tecido empresarial nacional, a escola propõe uma vasta oferta de cursos de pós-graduação na área da gestão. Nesse leque está, por exemplo, o “The Magellan MBA”, um MBA internacional totalmente lecionado em inglês e que atrai, anualmente, candidatos de todo o mundo. A escola oferece ainda um conjunto de pós-graduações de duração anual, programas de executivos, de curta e média duração, seminários de alta direção, programas de in-company training e serviços às empresas. Em 2014, um ano após celebrar 25 anos de vida, a Porto Business School inaugurou o seu novo campus, em Matosinhos. Alinhado com a estratégia de crescimento nacional e internacional da instituição, que passa por se posicionar no top 30 das Escolas de Negócios europeias , o novo complexo vai permitir aumentar o volume de atividade da escola, quer em número de programas oferecidos, quer em número de estudantes.');


--| CATEGORIES |--

-- Rever com a PO:

INSERT INTO categories (name) VALUES ('Desporto');
INSERT INTO categories (name) VALUES ('Música');
INSERT INTO categories (name) VALUES ('Tecnologia');
INSERT INTO categories (name) VALUES ('Biologia');
INSERT INTO categories (name) VALUES ('Química');
INSERT INTO categories (name) VALUES ('Física');
INSERT INTO categories (name) VALUES ('Cultura');
INSERT INTO categories (name) VALUES ('Arte');
INSERT INTO categories (name) VALUES ('Teatro');
INSERT INTO categories (name) VALUES ('Literatura');
INSERT INTO categories (name) VALUES ('Natureza');
INSERT INTO categories (name) VALUES ('Gastronomia');
INSERT INTO categories (name) VALUES ('Moda');
INSERT INTO categories (name) VALUES ('Lazer');
INSERT INTO categories (name) VALUES ('Comédia');